name: 'Composite Action Example'
description: 'A composite action to checkout code and set up Node.js'
# inputs:
#   python-version:
#     description: 'Python version to use'
#     required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4   
  
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        # python-version : ${{ inputs.python-version }}
        python-version : '3.11' 
        cache: 'pip'
        cache-dependency-path: requirements.txt
        
   
   
       
        
  
