name: 'Composite Action Example'
description: 'A composite action to checkout code and set up Node.js'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up python
      uses: aparnajyothi-y/setup-python@enhance-cache-dependency-path
      with:
        python-version : '3.12'
        cache: 'pip'
        cache-dependency-path: requirements.txt
        check-latest: true
        
        
    - name: Install dependencies
      run: pip install -r requirements.txt
      shell: bash
