name: 'Composite Action Example'
description: 'A composite action to checkout code and set up Node.js'
runs:
  using: 'composite'
  strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-13]
        python-version: ['3.9', '3.10', '3.11', '3.12','3.13t' ]
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up python
      uses: aparnajyothi-y/setup-python@Feature-request#476
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: requirements.txt
    - name: Install dependencies
      run: pip install -r requirements.txt
      shell: bash
