name: 'Composite Action Example'
description: 'A composite action to checkout code and set up Node.js'
inputs:
  python-version:
    description: 'Python version to use'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4  

   
  
    - name: Set up python
      uses: aparnajyothi-y/setup-python@temp-dir-#361
      # uses: priya-kinthali/setup-python@sample-361
      with:
        python-version : ${{ inputs.python-version }}
        python-version:  '3.11'
        cache: pip
        cache-dependency-path: requirements.txt
        
    - run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
         

   
     
    
       
   
   
        
   
   
       
        
  
