[tool.poetry]
name = "testing-cache123"
version = "0.1.0"
description = "My package description"
authors = ["gowridurgad <gowridurga.d@github.com>"]

[tool.poetry.dependencies]
python = ">=3.12"
requests = "^2.25.1"
