name: python cache

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        arch: ['x64', 'x86']
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.5'
          architecture: ${{ matrix.arch }}
          cache: 'poetry'
      - name: Use python
        run: |
          python --version
          poetry --version
          poetry install
