name: feature530

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
   

    steps:
      - uses: actions/checkout@v4
        

      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
           python-version-file: runtime.txt
