name: isssue1224
on: workflow_dispatch
jobs:
 tests:
  name: Unit tests and coverage
  runs-on: ubuntu-latest



  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - run: |
        python -m venv /env
        . /env/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
