name: Java CI gradle

on: 
  workflow_dispatch:

jobs:
  build:

    strategy:
      matrix:
        os: [ windows-2019, ubuntu-20.04 ]
        distribution: [ 'dragonwell' ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@main
        with:
          distribution: ${{ matrix.distribution }}
          java-version: '8'
          java-package: jdk
          architecture: x64
