name: Test Workflow1

on: 
    workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest

    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install coveralls
      run: |
        pip install coveralls



    - name: Run coveralls with login shell
      shell: bash -l {0}
      run: |
         export PYTHON_VERSION=$(python -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
         export PATH="/Users/runner/hostedtoolcache/Python/$PYTHON_VERSION/arm64/bin:/Library/Frameworks/Python.framework/Versions/$PYTHON_VERSION/bin:$PATH"
         coveralls --version
