name: issue641

on: 
   workflow_dispatch:

jobs:
  build:
    name: 'Ubuntu (Node 20, Deno 1.40, Java 21)'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@main
        with:
          distribution: 'dragonwell'
          java-version: '21'

     
