name: issue1188
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install poetry
        run: pipx install poetry
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'poetry'
      
  
      - name: Install dependencies (no-root, sync)
        run: poetry install --no-root --sync
      
      - name: Check Poetry Python version
        run: poetry env info
