name: Test Workflow1

on: 
    workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest


    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Install coveralls
      run: |
        pip install coveralls



    - name: Run coveralls with login shell
      shell: bash -l {0}
      run: |
        
         export PATH="/Users/runner/hostedtoolcache/Python/3.9/arm64/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:$PATH"
         coveralls --version
