name: crossplatform

on:
  workflow_dispatch:

jobs:
  check-cross:
    runs-on: macos-13
    strategy:
      fail-fast: false
      matrix:
        python-version:
         
          - "3.6" # should be *not* universal
         
        archname: [x86_64]
        include:
          - archname: x86_64
            arch: x86_64
            architecture: x64
            processor: i386
         
        
    steps:
      - name: Install missing libraries
        if: matrix.archname == 'x86_64'
        run: |
          brew install gettext
          brew link --force gettext
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      - name: arch(1)
        env:
          ARCHPREFERENCE: ${{ matrix.arch }}
        run: |
          proc=$(arch python -c "import platform; print(platform.processor())")
          echo $proc
          test $proc = ${{ matrix.processor }}
