name: isssue1224
on: workflow_dispatch
jobs:
 tests:
  name: Unit tests and coverage
  runs-on: ubuntu-latest



  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v6
      with:
        python-version: '3.12'
    - name: Check GLIBC version
      run: ldd --version
