name: issue1290

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
   

    steps:
      - uses: actions/checkout@v5
      - name: Prepare hostedtoolcache (rare, not recommended)
        run: |
          sudo mkdir -p /Users/runner/hostedtoolcache
          sudo chown $(whoami):$(id -gn) /Users/runner/hostedtoolcache

      - name: Set up Python 
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
         
          
     
