name: Numpy

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: macos-latest
       
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: 'pypy-3.9-v7.x'
          cache: 'pip'
      
      # - name: Upgrade pip and setuptools
      #   run: python -m pip install --upgrade pip setuptools

      # - name: Ensure compatible setuptools for hpy
      #   run: python -m pip install "setuptools>=64.0"

      - name: Install numpy (from wheel, not source)
        run: python -m pip install "numpy<1.25"
            
