name: poetryTest1
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install poetry
      run: pipx install poetry
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        cache: 'poetry'
    
    - name: Cache Poetry Dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-poetry-
    
    - name: Install dependencies
      run: poetry install
    
    - name: Check Poetry Python version
      run: poetry env info
