name: poetryTest1
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install poetry
      run: pipx install poetry
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Configure Poetry Virtual Environment Path
      run: poetry config virtualenvs.path ~/.cache/pypoetry/virtualenvs
    
    - name: Install dependencies
      run: poetry install
    
    - name: Check Poetry Python version
      run: poetry env info
