name: cachekey
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
   
      
       
       - uses: actions/checkout@v4
       - uses: aparnajyothi-y/setup-python@fix-overwirting
         with:
            python-version: '3.12'
            cache: 'pip'
            cache-dependency-path : temp/requirements.txt
            ocer-write: true

      
     
