name: Test file outside workspace
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create file outside workspace
        run: echo "pytest" > /tmp/requirements.txt
     
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: /temp/requirements.txt
      - run: pip install -r /tmp/requirements.txt
