name: testingbranch#361
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-13 ]
        
       
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
    
    
      - name: Set up python
        uses: aparnajyothi-y/setup-python@temp-dir-#361
        with:
             python-version:  '3.11'
             cache: poetry
             cache-dependency-path: poetry.lock
           
   
      - run: poetry install
     
         
    
