name: pip-testing

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-13]
        python_version: ["3.11", "3.12", "3.13"]
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: gowridurgad/setup-python@pipversion
      with:
        python-version : "${{ matrix.python_version }}"
        pip-version: '24'
        allow-prereleases: true
        
             
    - name: Check pip version
      run: pip --version

   

  
