name: Test Issue

on:
  workflow_dispatch:

jobs:
  Test_Dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Dotnet
        uses: actions/setup-dotnet@dependabot/npm_and_yarn/fast-xml-parser-4.4.1
        with:
          dotnet-version: '7.0'
      - run: dotnet build
      - run: dotnet test
