name: testing-1087

on:
  workflow_dispatch:

jobs:
  ubuntu-20-first:
    name: Step 1 - Ubuntu 24.04 container
    runs-on: self-hosted

    container:
      image: ubuntu:24.04 

    steps:
      - uses: actions/checkout@v6
      - name: Clear pre-mounted tool cache
        run: |
          echo "Before:"
          ls /__t/Python/ || echo "no Python dir"
          rm -rf /__t/Python
          echo "After:"
          ls /__t/Python/ || echo "cleared"

      - name: Setup Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

     

  ubuntu-24-second:
    name: Step 2 - Ubuntu 20.04 container
    runs-on: ubuntu-latest
    needs: ubuntu-20-first

    container:
      image: ubuntu:20.04

    steps:
      - uses: actions/checkout@v6
      - uses: actions/checkout@v6

      - name: Ensure Sudo is Installed
        run: |
          if ! command -v sudo &> /dev/null; then
            echo "sudo could not be found. Installing..."
            apt-get update && apt-get install -y sudo
          fi
      - name: Fix pip cache permissions
        run: sudo chown -R $(whoami) /github/home  
     

      - name: Setup Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
