name: Test file outside workspace
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create file outside workspace
        run: echo "pytest" > /tmp/requirements.txt
      - name: Setup Python
        uses: aparnajyothi-y/setup-python@fix-overwirting
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: tmp/requirements.txt
      - run: pip install -r tmp/requirements.txt
