name: testingbranch#361
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-13]       
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 
      - name: Set up python
        uses: aparnajyothi-y/setup-python@temp-dir-#361
        with:
      
            python-version:  '3.13'
            cache: pip
            cache-dependency-path: requirements.txt  
            freethreaded: true
      - run: pip install -r requirements.txt
     
         
    
